@startuml

title __PROFILEMVC's Class Diagram__\n

  package diploma {
    package diploma.profileMVC {
      class ProfileActivity {
          + addNewPatient()
      }
    }
  }
  

  package diploma {
    package diploma.profileMVC {
      class ProfileController {
          - surnameField : TextField
          - firstnameField : TextField
          - middlenameField : TextField
          - uraBox : ChoiceBox<String>
          - x101Box : ChoiceBox<String>
          - x102Field : TextField
          - x103Field : TextField
          - x104Box : ChoiceBox<String>
          - x105Box : ChoiceBox<String>
          - x106Box : ChoiceBox<String>
          - x107Box : ChoiceBox<String>
          - x108Box : ChoiceBox<String>
          - x109Box : ChoiceBox<String>
          - x110Box : ChoiceBox<String>
          - x111Box : ChoiceBox<String>
          - x112Box : ChoiceBox<String>
          - x113Box : ChoiceBox<String>
          - x114Box : ChoiceBox<String>
          - x115Field : TextField
          - x116Box : ChoiceBox<String>
          - x117Box : ChoiceBox<String>
          - x118Box : ChoiceBox<String>
          - x119Box : ChoiceBox<String>
          - x120Field : TextField
          - x121Field : TextField
          - x122Field : TextField
          - x123Field : TextField
          - x124Field : TextField
          - x125Field : TextField
          - x126Field : TextField
          - x127Field : TextField
          - backBtn : Button
          - x1Box : ChoiceBox<String>
          - x2Box : ChoiceBox<String>
          - x3Box : ChoiceBox<String>
          - x4Box : ChoiceBox<String>
          - x5Box : ChoiceBox<String>
          + initialize()
          + backToMenu()
          + addToDB()
      }
    }
  }
  

  ProfileController o-- ProfileActivity : profileActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
